### ISSUE TITLE
PodTransmutable cannot be implemented for char

### ISSUE THREAD

**Issue by BurntSushi** [nabijaczleweli/safe-transmute-rs#23]
Not all valid `u32` bit patterns are valid `char` values: https://doc.rust-lang.org/std/char/fn.from_u32_unchecked.html

**Comment by Enet4** [comment]
@BurntSushi Thank you very much for bringing that up! `char` should definitely not implement this trait.

**Comment by nabijaczleweli** [comment]
Released in [`v0.9.0`](https://github.com/nabijaczleweli/safe-transmute-rs/releases/tag/v0.9.0).
