### ISSUE TITLE
Rethink the name of "POD" related stuff

### ISSUE THREAD

**Issue by Enet4** [nabijaczleweli/safe-transmute-rs#41]
As once pointed out in #5, the concept of Plain Old Data object derived from the C or C++ specifications does not accurately portray what we mean. When a type `T` implements `PodTransmutable`, we are implying that all possible bit configurations of `N` bytes (where `N = size_of::<T>()`) would make a valid `T` (plus it has to be `Copy`, so that we avoid types with `Drop` implementations).
Since POD is really not a good name to describe this, I propose that we rename it. I've seen similar traits in the wild:
- `FromBytes`, as in [this Rust Belt Rust presentation](https://youtu.be/UfMOOxOGCmA?t=1688), it is implemented by types which fulfil veeeeery similar constraints: (1) any `size_of::<T>()` bytes make a valid `T` (2) for structs, arrays and unions, all fields are `FromBytes`; (3) For enums, they must be C-like and have exactly `2^b` variants (as in, it must be a power of two). What's neat about their `FromBytes` is that they implemented a `derive`, we could do that too.
- The [`plain`](https://docs.rs/plain) crate has a [`Plain`](https://docs.rs/plain/0.2.3/plain/trait.Plain.html) trait, which, by the given definition, can be implemented for a type if it is `repr(C)` and only contains data with no possible invalid values. What's unusual is that the conversion functions live in the trait as blanket implementations, and the trait is implemented for unsized array types.

Aaanyways, I am currently torn between the names `FromBytes` or maybe just `Transmutable`, but note that related function names, module name, and documentation will have to change accordingly. (after #40 is merged, of course).

**Comment by nabijaczleweli** [comment]
(Discussion on [chat.SO](https://chat.stackoverflow.com/transcript/message/45049621#45049621))

**Comment by nabijaczleweli** [comment]
Pretty sure this is also closable, what with having renamed all POD to Trivial?

**Comment by Enet4** [comment]
Indeed, #48 has already resolved this issue.
