### ISSUE TITLE
Make compilation target that tests for unaligned memory access

### ISSUE THREAD

**Issue by Enet4** [nabijaczleweli/safe-transmute-rs#42]
So far, our tests have all passed even when we read misaligned memory words. This happens because the target system is actually resilient to these, albeit with potential performance regressions, leading to the program behaving well anyway. As Rust's (assumed) memory model is more restrictive however, we don't want this to happen in practice.

So, we'd like to have a target triplet with some extra configurations that would force the program to seriously misbehave, so that we could detect these things in our tests. I heard that some ARM CPUs can be configured to trap on such an attempt, although I cannot find this online right now.

**Comment by Enet4** [comment]
I think `miri`, now in CI, does the checks that we were looking for. @nabijaczleweli  Can you double check (no pun intended) this and close?

**Comment by nabijaczleweli** [comment]
Tests work on my ARMs and `miri` does the job well enough
