### ISSUE TITLE
Update all documentation to cover the crate's new expectations

### ISSUE THREAD

**Issue by Enet4** [nabijaczleweli/safe-transmute-rs#54]
Right now we still have functions which, although safe to use, may leave a false impression with their documentation. Here's an example from `full::transmute_many`:

```rust
// Little-endian
assert_eq!(transmute_many::<u16, SingleManyGuard>(&[0x00, 0x01, 0x00, 0x02])?,
          &[0x0100, 0x0200]);
```

The test above does not guarantee a successful transmutation, because the input slice might not be 2-byte aligned in memory. The user would have to build these guarantees on their own:

- copy the data (`try_copy!`)
- perform byte-wise `read` operations and convert them to the intended target type (`byteorder` crate)
- transmute the base pointer and enforce unaligned reads (`ptr::read_unaligned`)

I propose that we provide better exception handling expectations in our doctest. At the same time, they should all be actually run (no `no_run`) and tests should pass with miri.

**Comment by nabijaczleweli** [comment]
[All tests ran, all cells finish](https://travis-ci.org/nabijaczleweli/safe-transmute-rs/builds/623344952)
