### ISSUE TITLE
Test suite is broken, unless things happen to align well by chance

### ISSUE THREAD

**Issue by saethlin** [nabijaczleweli/safe-transmute-rs#67]
The tests for this crate do not pass under Miri. As far as I can tell, there are at least two kinds of errors, the first one is this:
```
test src/lib.rs - (line 101) ... FAILED
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `[]`,
 right: `[256, 13330]`', src/lib.rs:16:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This error only reproduces under Miri, unfortunately. The problem here is that the slice being transmuted isn't aligned, so `try_copy!`'s copy mechanism is engaged and produces an empty array. At least I think that's what happens, I'll admit I'm a bit lost in the code.

Then a number of other doctests for unsafe functions fail, because alignment is a precondition of those functions but the alignment precondition is not satisfied by the doctests. In these cases I would advise using `cargo miri test` to find them as well, but these cases are all robustly detected with some debug assertions I'm proposing to add to the standard library: https://github.com/rust-lang/rust/pull/92686

I'd offer a PR, but I'm a bit confused by this codebase. It looks like you have some alignment helpers, but they're not used anywhere, but the lint against dead code is silenced on them, they're over-aligned, and there's a confusing comment over them: https://github.com/nabijaczleweli/safe-transmute-rs/blob/70c43e08904e2a313024cf4cefb826fd71aab226/tests/test_util/le_to_native.rs#L4-L13

How would you prefer to generate properly-aligned slices in tests? If you have some input, I can put up a PR that fixes the tests.

**Comment by nabijaczleweli** [comment]
It appears that we've done this in f3c892034d1624b99856c2a22c5ffa3b6bdd4e31, but just.. not fully? Either way, I've applied the forced-alignment structs to all the tests I saw were missing it (and, crucially, lib.rs#L101, which was the only one that miri failed on for me).

Could you please check if 6e9520a6d9acdf5eac96b5dc8a15aa241cd2e0b7 fixes this for you as well?

The lint for dead code is because this file gets included literally in the doctests. The alignment is, well, does it matter?

**Comment by saethlin** [comment]
This patch doesn't fix the underlying problem because though you've put these arrays in a wrapper with the requisite alignment, then `le_to_native` moves out of the container so you're back to just the alignment of `u8`. You should do the `le_to_native` conversion first, then put the array into a container, then when you grab a reference to `.0`, it will be properly aligned.

---

Ugh, this now passes Miri completely with the default flags by chance, see https://github.com/rust-lang/miri/pull/1990 if you're curious about me trying to fix that.

If you want to provoke Miri into checking alignment better, you need to run it a few times, setting `MIRIFLAGS=-Zmiri-seed=01` or various other numbers. Miri seeds a pRNG then uses this to shift objects around a bit, with the hopes that casting to a more-aligned pointer type without doing the required checks will at least sometimes produce an alignment error in evaluation. So to see errors with that commit you need to run `MIRIFLAGS=-Zmiri-seed=01 cargo miri test`. Miri is a nightly-only component, I think it will be back tomorrow.

**Comment by nabijaczleweli** [comment]
Right, of course, I forgot we move out of the slices in some implementations.

Not sure what you mean by miri "being back tomorrow", but this passed
```sh
for i in $({ echo obase=16; seq 255; } | bc | sed 's/^.$/0\0/'); do MIRIFLAGS=-Zmiri-seed=$i cargo +nightly miri test || { echo $i; break; }; done
```
for me, so If you'd try the current HEAD (at least 269998b6f20cf27a0e8d69c8c55b2735a3f27f7e) on your end, too, that'd be great.

**Comment by saethlin** [comment]
Miri wasn't available on the past few nightly toolchains, so if you had an up-to-date nightly too many hours ago and tried to `rustup component add nightly` it would just fail.

It looks like everything passes on my end too. Thanks so much for fixing this!
